### ISSUE TITLE
Incorrect description

### ISSUE THREAD

**Issue by jschwartzenberg** [kosyak/naclports_samsung-smart-tv#1]
In the description it says "Does not work at the moment.", but I tried the first port agg-demo and managed to get it to work in both the emulator and on my Samsung Smart TV :+1:

**Comment by kosyak** [comment]
Wow, great :) Haven't hacked this for ages. Hope it's not extremely outdated now...

**Comment by jschwartzenberg** [comment]
It's interesting to get things to work. It seems DOSBox and ScummVM do at least something in the emulator, but on the TV, they both get stuck at the loading screen (of the TV). Did you have to make a lot of changes to this branch? How far did you manage to get yourself?

The pepper versions that the TVs supports are also outdated, so it's doesn't seem bad that your tree is as well :)

**Comment by kosyak** [comment]
The main reason for me to port this was to make ImageMagick library work - so almost all of changes were to make it and its dependencies compile (I guess I was not impressed with the performance of the library and then abandoned the project).

You can easily find my commits - it's only under 10 of them: they focused mainly on modifying ENVs, removing unnecessary toolchains/platforms.

**Comment by jschwartzenberg** [comment]
I see. Did you use pepper_25 or pepper_31 back then?

**Comment by kosyak** [comment]
I think I compiled for pepper_25 and pepper_27.
